### ISSUE TITLE
CoreML model processing time is almost twice as much as when the app is active

### ISSUE THREAD

**Issue by hsnawn** [hollance/neural-engine#14]
Great article! I think it's a great idea to write this on GitHub instead of a blog post. I am running a CoreML model on iPhone 8. I am using `cpuOnly` as I want the model to process in the background. I have observed a strange thing. The model takes approximately 8 seconds to process one image when the app is active or in background mode. But if I open Chrome or Safari while my App is running in the background the processing speed per image suddenly drops to approximately 3 seconds per image. Why is it so and how can I decrease processing in all cases?

**Comment by hollance** [comment]
I don't work for Apple tech support. ;-) A question like this is better asked on StackOverflow or the Apple Developer Forums.
