### ISSUE TITLE
[Question] Have you tried A17 Pro Neural Engine?

### ISSUE THREAD

**Issue by y-ich** [hollance/neural-engine#27]
Hi, Hollance san.

Have you tried A17 Pro Neural Engine?

Apple claim that it has 35TOPS, which is a big leap performance boost.
But Geekbench ML shows that it is a just little.
iPhone16,1(iPhone 15 Pro) = 3402
iPhone15,2(iPhone 14 Pro) = 3349
https://browser.geekbench.com/ml/v0/inference

I wonder that Apple may implement 4bit INT OPs for internal use, and legacy performance is almost same, just clock up.
What do you think about it?

**Comment by hollance** [comment]
I have not tried it but it wouldn't surprise me if the performance we can get as third-party developers isn't the maximum, since we're limited to using the Neural Engine through Core ML.

**Comment by y-ich** [comment]
Thank you for your comments!
I hope that Apple will make all performance of neural engine open some day.

About Geekbench ML, they test CPU, GPU, and Core ML resources separately using TensorFlow Lite.
Comparing those score, I think that Geekbench ML Core ML uses Neural Engine normally.

**Comment by hollance** [comment]
Does the TensorFlow Lite test use the CoreMLDelegate, though? (I don't know, never looked at it.) But even then there's no guarantee the model actually runs on the Neural Engine.

**Comment by y-ich** [comment]
Yes, they test the performances of CPU, GPU, and Core ML separately.
The scores show Core ML uses Neural Engine.
