### ISSUE TITLE
Since ANE accelerate neural network model, how could it benefit traditional cpu task? I mean in Apple M1.

### ISSUE THREAD

**Issue by pessimo** [hollance/neural-engine#4]
With the release of Apple M1, a lot of people start to compare M1 with intel cpu, even nvida gpu. But to my understanding, ANE should not intervene normal tasks handled by gpu for example rendering, nor should it intervene normal tasks handled by cpu... npu should focus on their own business... and it’s more confusing to integrate NPU inside chips(maybe they should have their own position)

Sorry to ask question here and make GitHub a little bit like a forum...

**Comment by hollance** [comment]
Who knows? There appears to be no public API for using the ANE. If you want to use the ANE, you have to make a Core ML model (neural network) and hope that Core ML will actually run it on the ANE.
